### ISSUE TITLE
Subflow crashes Node Red

### ISSUE THREAD

**Issue by ilexpl01** [serek4/node-red-sofar-ktl-x-request#6]
Hi. 

Thx 4 for the subflow. It almost works great 🙂

Unfortunately from time to time it crashes my node red with error:

25 Jul 21:35:28 - [red] Uncaught Exception:
25 Jul 21:35:28 - [error] RangeError: The value of "offset" is out of range. It must be >= 0 and <= 7. Received 9
    at boundsError (node:internal/buffer:88:9)
    at Buffer.readUInt16BE (node:internal/buffer:334:5)
    at _readFC3or4 (/data/node_modules/@open-p4nr/modbus-serial/index.js:160:26)
    at ModbusRTU._onReceive (/data/node_modules/@open-p4nr/modbus-serial/index.js:560:17)
    at TcpPort.emit (node:events:519:28)
    at Socket.<anonymous> (/data/node_modules/@open-p4nr/modbus-serial/ports/tcpport.js:93:24)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Socket.Readable.push (node:internal/streams/readable:390:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)

I use dockeriized node red:

25 Jul 21:36:02 - [info] Node-RED version: v4.0.2
25 Jul 21:36:02 - [info] Node.js  version: v20.15.0
25 Jul 21:36:02 - [info] Linux 4.4.302+ x64 LE

Any advice ?

**Comment by serek4** [comment]
This errors seems to come from @open-p4nr/modbus-serial library, and this subflow do not use this library.
Communication with logger is done using node-red default `tcp request` node.
So i don't think this subflow is causing this errors.
Only reason, i can think of, this errors are releated to this subflow is that you are connected to logger with this subflow and modbus-serial at the same time.

**Comment by ilexpl01** [comment]
thx 4 reply.

Reported the problem also here:

[https://github.com/BiancoRoyal/node-red-contrib-modbus/issues/480](url)
